env:
  matrix:
    - TZ=Europe/London
    - TZ=America/Los_Angeles

os:
  - linux

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

before_install:	
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install framed titling; fi

r_packages:
  - covr
  - rmarkdown

after_success:
  - Rscript -e 'covr::codecov()'

