env:
  matrix:
    - TZ=Europe/London
    - TZ=America/Los_Angeles

os:
  - linux
  - osx

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

before_install:	
  - if [[ "$OSTYPE" == "osx" ]]; then sudo tlmgr install framed titling; fi

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
